# Below code creates 'namespace-admin-rbg' for multiple users. RoleBinding which attaches the AAD Group or users to a Role with Namespace admin priveleges. 
# Note: KIDs ust be in uppercase only.
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
subjects:
- kind: User
  name: #Place your KID
- kind: User #another user
  name: #Place your partner's KID
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: namespace-admin # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io
